name: linting testing building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.18.0']

    steps:
      - uses: actions/checkout@v2
      - name: Setting up Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version}}
      - name: Install modules
        run: npm install
      - name: Build production project
        run: npm run build:prod
        if: always()
      - name: Lint TypeScript
        run: npm run lint:ts
        if: always()
      - name: Lint CSS
        run: npm run lint:scss
        if: always()
      - name: Unit testing
        run: npm run test:unit
#      - name: build storybook
#        run: npm run storybook:build
#      - name: screenshot testing
#        run: npm run test:ui:ci
